/**
 * Turn a repeated Bash command into a copyable, reusable wrapper (#1803, epic
 * #1485). The Repeated-Commands surface (Tools view) and the
 * `workflow.repeated-commands` detector both list commands a session ran 3+
 * times; this is the read-side primitive that lets the user STOP re-typing them
 * by copying a ready-made script wrapper instead of just reading a label.
 *
 * Pure string transformation — no fs, no network, no `@api-client` — so it is
 * safe in both the server and SPA (upload) builds.
 */

import { shellQuote } from './shell-quote';

/**
 * Derive a short, filesystem-safe slug for the wrapper script name from the
 * command's first token (the program being invoked). Falls back to `command`.
 */
function commandSlug(command: string): string {
  const firstToken = command.trim().split(/\s+/)[0] ?? '';
  // Strip a leading path so `./scripts/foo.sh` → `foo`.
  const base = firstToken.split('/').pop() ?? firstToken;
  const slug = base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'command';
}

/**
 * Pick a heredoc delimiter that does NOT appear as a standalone line in the
 * command body, so the body — even a multi-line command that itself contains a
 * line `SH` (e.g. one writing its own `<<'SH'` heredoc) — can never terminate
 * the wrapper's heredoc early and leak trailing lines back to the top-level
 * shell. Deterministic (no randomness): for the normal single-line case the
 * delimiter stays plain `SH`, so existing output/tests are unchanged; on a
 * collision it deterministically suffixes `SH_1`, `SH_2`, … until it is unique.
 */
function safeHeredocDelimiter(body: string): string {
  const lines = body.split('\n');
  const collides = (candidate: string): boolean =>
    lines.some((line) => line === candidate);
  let delimiter = 'SH';
  for (let n = 1; collides(delimiter); n += 1) {
    delimiter = `SH_${n}`;
  }
  return delimiter;
}

/**
 * Build a copyable shell-script wrapper for a command the user keeps re-running.
 * The snippet creates an executable `scripts/<slug>.sh`, so the next session
 * runs one stable entry point instead of repeating the literal steps. The
 * command body is single-quoted, so any command — pipes, flags, quotes — is
 * preserved exactly.
 */
export function wrapCommandSnippet(command: string): string {
  const trimmed = command.trim();
  const slug = commandSlug(trimmed);
  const script = `scripts/${slug}.sh`;
  const delimiter = safeHeredocDelimiter(trimmed);
  return [
    `mkdir -p scripts && cat > ${script} <<'${delimiter}'`,
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '# Generated by Claude Coach from a repeated command — edit freely.',
    trimmed,
    delimiter,
    `chmod +x ${script}`,
    `# Run it next time with: ./${script}`,
  ].join('\n');
}

/**
 * Build a copyable one-line shell alias for a command the user keeps re-running,
 * suitable for pasting into `~/.bashrc` / `~/.zshrc`. Shorter than the script
 * wrapper for commands that are essentially a single invocation.
 */
export function aliasCommandSnippet(command: string): string {
  const trimmed = command.trim();
  const slug = commandSlug(trimmed);
  return `alias ${slug}=${shellQuote(trimmed)}`;
}
