// Sample Workflow-tool runs for the marketing SPA (issue #537).
//
// The Workflow view (#435) reads `workflows/wf_*.json` run manifests via the
// `/api/workflows` endpoint. Like Insights and Memories, that data CANNOT ride
// the upload zip (the uploader keeps only `.jsonl`), and the SPA stub returns
// `{ runs: [] }`, so in demo mode the ledger would render empty. This module
// builds a representative raw `WorkflowsResponse` that App.tsx runs through the
// real `parseWorkflows` when sample mode activates.
//
// Lazy-imported (only when demo mode turns on) so it stays off the cold-load
// path and out of real uploads. Runs are templated over the ACTUAL sample
// session ids (passed in at load time) so each run's parent-session link joins
// a real demo session — mirroring how sample-insights templates its facets.
// Content is entirely synthetic; no `/api/` literals (spa-boundary clean).

import type { WorkflowsResponse, RawWorkflowRun } from './parse-workflows';
import { CURRENT_MODEL_IDS } from './model-registry';

const MODELS = {
  opus: CURRENT_MODEL_IDS.opus,
  sonnet: CURRENT_MODEL_IDS.sonnet,
  haiku: CURRENT_MODEL_IDS.haiku,
};

// Fixed timestamps (sample window matches the corpus's 2026-05 base) so the
// ledger order is deterministic. Newest run first after parseWorkflows sorts.
const T_REVIEW = Date.UTC(2026, 4, 26, 16, 12, 0);
const T_MIGRATE = Date.UTC(2026, 4, 24, 10, 30, 0);
const T_RESEARCH = Date.UTC(2026, 4, 21, 9, 5, 0);

/**
 * Build the sample workflow ledger, binding each run to one of the demo's real
 * session ids so the run-detail "parent session" link resolves. `sessionIds`
 * comes from the loaded sample bundle; an empty array is tolerated (the runs
 * still parse, just with no parent-session join).
 */
export function buildSampleWorkflows(sessionIds: string[]): WorkflowsResponse {
  const sid = (i: number): string => sessionIds[i % sessionIds.length] ?? '';

  const runs: RawWorkflowRun[] = [
    {
      runId: 'wf_review_a1b2c3',
      workflowName: 'review-changes',
      status: 'completed',
      startTime: T_REVIEW,
      durationMs: 4 * 60 * 1000,
      agentCount: 5,
      totalTokens: 182_400,
      totalToolCalls: 63,
      defaultModel: MODELS.sonnet,
      sessionId: sid(0),
      phases: [
        { title: 'Review', detail: 'Review changed files across dimensions' },
        { title: 'Verify', detail: 'Adversarially verify each finding' },
      ],
      workflowProgress: [
        { type: 'workflow_phase', phaseIndex: 0, title: 'Review' },
        {
          type: 'workflow_agent',
          index: 0,
          label: 'review:correctness',
          phaseIndex: 0,
          phaseTitle: 'Review',
          model: MODELS.sonnet,
          state: 'done',
          startedAt: T_REVIEW,
          durationMs: 95_000,
          tokens: 48_200,
          toolCalls: 21,
          promptPreview: 'Review the diff for logic errors and unhandled edge cases.',
          resultPreview: 'Found 2 candidate issues: an unguarded null in the cart reducer and a missing await.',
        },
        {
          type: 'workflow_agent',
          index: 1,
          label: 'review:perf',
          phaseIndex: 0,
          phaseTitle: 'Review',
          model: MODELS.sonnet,
          state: 'done',
          startedAt: T_REVIEW + 1_000,
          durationMs: 88_000,
          tokens: 41_900,
          toolCalls: 16,
          promptPreview: 'Review the diff for N+1 queries and loop-heavy transforms.',
          resultPreview: 'One N+1: the orders list refetches the customer per row instead of joining.',
        },
        { type: 'workflow_phase', phaseIndex: 1, title: 'Verify' },
        {
          type: 'workflow_agent',
          index: 2,
          label: 'verify:cart-null',
          phaseIndex: 1,
          phaseTitle: 'Verify',
          model: MODELS.haiku,
          state: 'done',
          startedAt: T_REVIEW + 100_000,
          durationMs: 40_000,
          tokens: 18_700,
          toolCalls: 9,
          promptPreview: 'Adversarially verify: unguarded null in the cart reducer. Try to refute.',
          resultPreview: 'Confirmed real — empty cart hits the null path; reproduced in a unit test.',
        },
        {
          type: 'workflow_agent',
          index: 3,
          label: 'verify:missing-await',
          phaseIndex: 1,
          phaseTitle: 'Verify',
          model: MODELS.haiku,
          state: 'done',
          startedAt: T_REVIEW + 102_000,
          durationMs: 37_000,
          tokens: 16_300,
          toolCalls: 7,
          promptPreview: 'Adversarially verify: missing await. Try to refute.',
          resultPreview: 'Refuted — the call is fire-and-forget by design; not a bug.',
        },
        {
          type: 'workflow_agent',
          index: 4,
          label: 'verify:n-plus-one',
          phaseIndex: 1,
          phaseTitle: 'Verify',
          model: MODELS.haiku,
          state: 'done',
          startedAt: T_REVIEW + 104_000,
          durationMs: 39_000,
          tokens: 17_200,
          toolCalls: 8,
          promptPreview: 'Adversarially verify: N+1 in orders list. Try to refute.',
          resultPreview: 'Confirmed real — 1 + N queries observed; a JOIN collapses it to one.',
        },
      ],
    },
    {
      runId: 'wf_migrate_d4e5f6',
      workflowName: 'migrate-charts',
      status: 'completed',
      startTime: T_MIGRATE,
      durationMs: 6 * 60 * 1000,
      agentCount: 3,
      totalTokens: 134_800,
      totalToolCalls: 71,
      defaultModel: MODELS.sonnet,
      sessionId: sid(1),
      phases: [
        { title: 'Discover', detail: 'Find every chart import to migrate' },
        { title: 'Transform', detail: 'Port each file off the deprecated lib' },
      ],
      workflowProgress: [
        { type: 'workflow_phase', phaseIndex: 0, title: 'Discover' },
        {
          type: 'workflow_agent',
          index: 0,
          label: 'discover:chart-imports',
          phaseIndex: 0,
          phaseTitle: 'Discover',
          model: MODELS.haiku,
          state: 'done',
          startedAt: T_MIGRATE,
          durationMs: 32_000,
          tokens: 14_500,
          toolCalls: 11,
          promptPreview: 'List every file importing the deprecated charting lib.',
          resultPreview: 'Found 2 files: the dashboard overview and the trends panel.',
        },
        { type: 'workflow_phase', phaseIndex: 1, title: 'Transform' },
        {
          type: 'workflow_agent',
          index: 1,
          label: 'transform:overview',
          phaseIndex: 1,
          phaseTitle: 'Transform',
          model: MODELS.sonnet,
          state: 'done',
          agentType: 'general-purpose',
          startedAt: T_MIGRATE + 35_000,
          durationMs: 140_000,
          tokens: 61_200,
          toolCalls: 33,
          promptPreview: 'Port the dashboard overview chart to the new lib; keep the API identical.',
          resultPreview: 'Migrated; visual diff matches and the chart test passes.',
        },
        {
          type: 'workflow_agent',
          index: 2,
          label: 'transform:trends',
          phaseIndex: 1,
          phaseTitle: 'Transform',
          model: MODELS.sonnet,
          state: 'done',
          agentType: 'general-purpose',
          startedAt: T_MIGRATE + 36_000,
          durationMs: 151_000,
          tokens: 59_100,
          toolCalls: 27,
          promptPreview: 'Port the trends panel chart to the new lib; keep the API identical.',
          resultPreview: 'Migrated; legend spacing needed one tweak, now matches the design.',
        },
      ],
    },
    {
      runId: 'wf_research_07a8b9',
      workflowName: 'deep-research',
      status: 'completed',
      startTime: T_RESEARCH,
      durationMs: 5 * 60 * 1000,
      agentCount: 4,
      totalTokens: 156_000,
      totalToolCalls: 48,
      defaultModel: MODELS.opus,
      sessionId: sid(2),
      phases: [
        { title: 'Search', detail: 'Multi-modal sweep across sources' },
        { title: 'Synthesize', detail: 'Cross-check and write the report' },
      ],
      workflowProgress: [
        { type: 'workflow_phase', phaseIndex: 0, title: 'Search' },
        {
          type: 'workflow_agent',
          index: 0,
          label: 'search:rate-limiter-patterns',
          phaseIndex: 0,
          phaseTitle: 'Search',
          model: MODELS.sonnet,
          state: 'done',
          startedAt: T_RESEARCH,
          durationMs: 64_000,
          tokens: 33_400,
          toolCalls: 12,
          promptPreview: 'Survey token-bucket vs sliding-window rate limiters and their trade-offs.',
          resultPreview: 'Token bucket favours bursty clients; sliding window is fairer under steady load.',
        },
        {
          type: 'workflow_agent',
          index: 1,
          label: 'search:per-client-fairness',
          phaseIndex: 0,
          phaseTitle: 'Search',
          model: MODELS.sonnet,
          state: 'done',
          startedAt: T_RESEARCH + 1_000,
          durationMs: 61_000,
          tokens: 31_800,
          toolCalls: 10,
          promptPreview: 'How do production limiters keep one client from exhausting a shared pool?',
          resultPreview: 'Per-client keys + a global ceiling; reject early with Retry-After.',
        },
        { type: 'workflow_phase', phaseIndex: 1, title: 'Synthesize' },
        {
          type: 'workflow_agent',
          index: 2,
          label: 'synthesize:report',
          phaseIndex: 1,
          phaseTitle: 'Synthesize',
          model: MODELS.opus,
          state: 'done',
          startedAt: T_RESEARCH + 140_000,
          durationMs: 120_000,
          tokens: 57_000,
          toolCalls: 14,
          promptPreview: 'Synthesize the findings into a recommendation for the rate limiter.',
          resultPreview: 'Recommend per-client token buckets with a global cap; cited 4 sources.',
        },
        {
          type: 'workflow_agent',
          index: 3,
          label: 'verify:claims',
          phaseIndex: 1,
          phaseTitle: 'Synthesize',
          model: MODELS.haiku,
          state: 'done',
          startedAt: T_RESEARCH + 142_000,
          durationMs: 44_000,
          tokens: 19_400,
          toolCalls: 12,
          promptPreview: 'Adversarially verify each cited claim resolves to its source.',
          resultPreview: 'All 4 citations resolved; one wording softened to match the source.',
        },
      ],
    },
    // An aborted run that left an agent in an error state — drives
    // workflow.failed-workflow-runs (#635).
    {
      runId: 'wf_optimize_d4e5f6',
      workflowName: 'optimize-clustering',
      status: 'aborted',
      startTime: Date.UTC(2026, 4, 25, 14, 0, 0),
      durationMs: 2 * 60 * 1000,
      agentCount: 3,
      totalTokens: 88_200,
      totalToolCalls: 19,
      defaultModel: MODELS.sonnet,
      sessionId: sid(2),
      phases: [{ title: 'Experiment', detail: 'Run parallel clustering experiments' }],
      workflowProgress: [
        { type: 'workflow_phase', index: 0, title: 'Experiment' },
        {
          type: 'workflow_agent',
          index: 0,
          label: 'experiment:k=4',
          phaseIndex: 0,
          phaseTitle: 'Experiment',
          model: MODELS.sonnet,
          state: 'done',
          startedAt: Date.UTC(2026, 4, 25, 14, 0, 10),
          durationMs: 40_000,
          tokens: 41_000,
          toolCalls: 9,
          promptPreview: 'Cluster with k=4 and score the silhouette.',
          resultPreview: 'silhouette 0.42',
        },
        {
          type: 'workflow_agent',
          index: 1,
          label: 'experiment:k=6',
          phaseIndex: 0,
          phaseTitle: 'Experiment',
          model: MODELS.sonnet,
          state: 'error',
          startedAt: Date.UTC(2026, 4, 25, 14, 0, 12),
          durationMs: null,
          tokens: 47_200,
          toolCalls: 10,
          promptPreview: 'Cluster with k=6 and score the silhouette.',
          resultPreview: 'ERROR: worker exceeded memory; run aborted.',
        },
      ],
    },
    // A wide fan-out whose token spend dwarfs the other runs — drives
    // workflow.runaway-workflow-cost (#635): >3x the median, well over the floor.
    {
      runId: 'wf_audit_99aa88',
      workflowName: 'exhaustive-audit',
      status: 'completed',
      startTime: Date.UTC(2026, 4, 27, 11, 0, 0),
      durationMs: 22 * 60 * 1000,
      agentCount: 18,
      totalTokens: 620_000,
      totalToolCalls: 410,
      defaultModel: MODELS.opus,
      sessionId: sid(1),
      phases: [
        { title: 'Find', detail: 'Fan out finders across the codebase' },
        { title: 'Verify', detail: 'Adversarially verify each finding' },
      ],
      workflowProgress: [
        { type: 'workflow_phase', index: 0, title: 'Find' },
        {
          type: 'workflow_agent',
          index: 0,
          label: 'find:round1',
          phaseIndex: 0,
          phaseTitle: 'Find',
          model: MODELS.opus,
          state: 'done',
          startedAt: Date.UTC(2026, 4, 27, 11, 0, 20),
          durationMs: 120_000,
          tokens: 210_000,
          toolCalls: 140,
          promptPreview: 'Find every bug across the repository.',
          resultPreview: '37 candidate findings surfaced.',
        },
        {
          type: 'workflow_agent',
          index: 1,
          label: 'verify:fanout',
          phaseIndex: 1,
          phaseTitle: 'Verify',
          model: MODELS.opus,
          state: 'done',
          startedAt: Date.UTC(2026, 4, 27, 11, 3, 0),
          durationMs: 180_000,
          tokens: 410_000,
          toolCalls: 270,
          promptPreview: 'Adversarially verify all 37 findings in parallel.',
          resultPreview: '12 confirmed real; 25 refuted.',
        },
      ],
    },
  ];

  return { runs };
}
