// SPA-upload ↔ server-ingest dataset parity gate (#2951).
//
// The free tier's correctness rests on the parsers being isomorphic: the
// server runs src/lib/parse-*.ts over the live ~/.claude tree
// (scripts/ingest.mjs → assembleDataset()), the SPA runs the IDENTICAL modules
// browser-side over an uploaded zip (buildUploadDataset). Until this test,
// nothing asserted the two paths actually produce equivalent datasets for the
// same input tree — the strongest untested product invariant the v0.6.0
// architecture survey found.
//
// Design: one fixture (the deterministic sample corpus that already drives the
// SPA demo build) is fed to BOTH pipelines from identical bytes — zipped for
// the upload path, written to a temp $HOME/.claude for the server path — and
// the datasets are compared over every shared key after applying the server's
// OWN declared wire-shaping (slimSessionTimeline, stripToolCommandBodies) and
// removing its provenance stamps (sourceId/harness). Every top-level key of
// assembleDataset()'s return must be classified below (parity, server-only, or
// fixture-empty); an unclassified new key fails the test, so the divergence
// allowlist is a reviewed boundary inventory like ENTERPRISE_ROUTE_INVENTORY.
//
// Run: node --import ./scripts/register-ts.mjs --test scripts/upload-server-parity.test.mjs

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { Blob } from 'node:buffer';
import { zipSync } from 'fflate';

import { buildSampleCorpus, corpusZipEntries } from './sample-data/build-corpus.mjs';

// ── The divergence allowlist: the documented contract of what the SPA tier ──
// ── legitimately lacks. Every entry carries its reason. Adding a key to    ──
// ── assembleDataset() forces a conscious, reviewable classification here.  ──

/**
 * Keys compared for parity. Maps the server dataset key to how the SPA fold
 * produces it. Comparison happens after `normalize()` below.
 */
export const PARITY_KEYS = [
  'entries',
  'tokenData',
  'toolData',
  'toolInventories',
  'timelines',
  'apiErrors',
  'permissionRows',
  'permissionChanges',
  'agentSettings',
  'attribution',
  'runtimeEvents',
  'churnGeometry',
  'valueFlow',
];

/**
 * Per-parity-key fields excluded from the row comparison because the two tiers
 * legitimately source them from tier-specific context (project/title
 * attribution), NOT from the shared parser output. The parsed CONTENT of every
 * row (token counts, tool calls, timeline shape, error codes, permission
 * rules) is still compared exactly — only these attribution stamps are
 * normalized away. Each is a documented, reviewed asymmetry; convergence is
 * tracked in the follow-up issue filed from #2951.
 */
export const FIELD_NORMALIZE = {
  // Server inlines the session title (deriveEntries, from the blob-cache
  // `title` column) onto every history entry; the upload transcript-entry
  // collector passes title=null (#978), so the SPA entry has no title. The
  // display/timestamp/project/sessionId — everything the entry MEANS — match.
  entries: ['title'],
  // The upload path passes the project decoded from the zip directory
  // (projects/<slug>/) into parseSessionJsonl; the server signal calls it with
  // no project arg and falls back to the transcript's own `cwd` (#1765), which
  // this synthetic corpus's turns don't carry. Every token/cache/context
  // COUNT is identical; only the derived project label + its short form differ.
  tokenData: ['project', 'projectShort'],
};

/**
 * Server-only keys the SPA structurally cannot produce from an upload, with
 * the reason each is out of the free tier's reach.
 */
export const SERVER_ONLY_KEYS = {
  schemaVersion: 'response envelope, not parser data',
  generatedAt: 'response envelope, not parser data',
  windowStart: 'response envelope, not parser data',
  windowEnd: 'response envelope, not parser data',
  units: 'response envelope (numeric-field unit hints)',
  sources: 'multi-source addressing exists only server-side (resolveSources)',
  sourceId: 'top-level single-source provenance stamp (server addressing envelope)',
  harness: 'top-level single-source provenance stamp (server addressing envelope)',
  liveConfig:
    'reads live settings.json; the upload path BLOCKS settings.json as sensitive (unzip-upload SENSITIVE_FILES)',
  repoMap:
    'host-produced usage-data/repo-map artifacts generated by npm run refresh:repo-map on the host (ADR 0007)',
  gitOutcomes: 'opt-in CHD_GIT_OUTCOMES gh/git egress (#1757); server-only by the non-local-data rule',
  docGraph: 'server-side repo-docs walk of the live checkout, not part of a ~/.claude export',
  docsMap: 'server-side repo-docs walk of the live checkout, not part of a ~/.claude export',
  docIssueSnapshot: 'opt-in CHD_DOC_ISSUES GitHub GraphQL fetch (#2710); server-only',
  shadowCalls: 'reads ~/.claude/shadow-calls ledgers outside the export bundle shape',
  localCalibration: 'server-side calibration ledger join',
  modelEvalSummary: 'server-side model-eval ledger join',
  reviewEvents: 'opt-in GitHub review-event sync (#1127); server-only',
  semanticIntent: 'opt-in server-side semantic-intent artifacts',
  taskSteering: 'derived server-side at assembly (#2203 steer telemetry join)',
  // taskSuccess/assistantFeatures/deceitSignals/secretsAtRest ARE per-session
  // SESSION_SIGNALS (structurally like churnGeometry/valueFlow, which we DO
  // compare); they're server-only here only because runUploadParse
  // (src/lib/upload-parse.ts) never wires their parsers into the upload passes.
  // A wiring gap, not a structural one — graduating them to PARITY_KEYS is
  // tracked with the other convergence follow-ups.
  taskSuccess: 'per-session signal parser not wired into runUploadParse (upload-parse.ts)',
  assistantFeatures: 'per-session signal parser not wired into runUploadParse (upload-parse.ts)',
  promptAnalysis: 'derived server-side at assembly (prompt traits)',
  deceitSignals: 'per-session signal parser not wired into runUploadParse (upload-parse.ts)',
  secretsAtRest: 'per-session signal parser not wired into runUploadParse (upload-parse.ts)',
  recommendations: 'server-computed envelope; the browser is a pure viewer since #2719',
  externalGuidance:
    'repo-shipped curated first-party guidance seed (data/external-guidance/, EXTERNAL_GUIDANCE_DIR) the server always loads — not derived from the uploaded ~/.claude tree',
};

/**
 * Keys both sides CAN produce but this transcripts+history fixture does not
 * exercise: parity here means BOTH sides yield empty. A richer fixture can
 * graduate a key into a real content comparison.
 */
export const FIXTURE_EMPTY_KEYS = [
  'memories',
  'workflows',
  'tasks',
  'teams',
  'sessionRegistry',
  'telemetry',
  'modelLatency',
  'debugLogs',
  'statsCache',
  'fileHistory',
  'plans',
  'updateResults',
  'mcpAuth',
  'configBackups',
];

// ── Fixture plumbing ──────────────────────────────────────────────────────

function buildServerHome(corpus) {
  const home = join(tmpdir(), `chd-2951-home-${randomUUID()}`);
  const claude = join(home, '.claude');
  mkdirSync(claude, { recursive: true });
  writeFileSync(join(claude, 'history.jsonl'), corpus.historyJsonl);
  for (const s of corpus.sessions) {
    const proj = join(claude, 'projects', s.slug);
    mkdirSync(proj, { recursive: true });
    writeFileSync(join(proj, `${s.sessionId}.jsonl`), s.jsonl);
  }
  return home;
}

// Import ingest fresh with HOME + CHD_DB_PATH pointed at the fixture. Both are
// read at module load, so set them BEFORE the import; the cache-buster query
// keeps each import a distinct module instance (same recipe as
// transcript-cache-parity.test.mjs).
async function runServerPipeline(home) {
  const dbPath = join(tmpdir(), `chd-2951-db-${randomUUID()}.db`);
  const prevHome = process.env.HOME;
  const prevDb = process.env.CHD_DB_PATH;
  const prevClaudeDir = process.env.CLAUDE_DIR;
  process.env.HOME = home;
  process.env.CHD_DB_PATH = dbPath;
  delete process.env.CLAUDE_DIR;
  try {
    const mod = await import(`./ingest.mjs?parity=${randomUUID()}`);
    await mod.ingest();
    return { dataset: await mod.assembleDataset(), dbPath };
  } finally {
    process.env.HOME = prevHome;
    if (prevDb === undefined) delete process.env.CHD_DB_PATH;
    else process.env.CHD_DB_PATH = prevDb;
    if (prevClaudeDir !== undefined) process.env.CLAUDE_DIR = prevClaudeDir;
  }
}

// Run the REAL upload pipeline (inflate + 11 parse passes + collectors) over
// the zipped corpus and fold its emits exactly the way App.tsx applies them
// for a single fresh upload (no prior state, so replace-shaped dedup reduces
// to concatenation; permissions flatten into rows + changes; entries are
// history ∪ transcript with transcript winning by sessionId — via the real
// unionEntries).
async function runUploadPipeline(zipBytes) {
  const { buildUploadDataset } = await import('../src/lib/upload-dataset.ts');
  const { unionEntries } = await import('../src/lib/parse-history.ts');

  const folded = {
    entries: [],
    tokenData: [],
    toolData: [],
    toolInventories: [],
    timelines: [],
    apiErrors: [],
    permissionRows: [],
    permissionChanges: [],
    agentSettings: [],
    attribution: [],
    runtimeEvents: [],
    churnGeometry: [],
    valueFlow: [],
    memories: [],
    workflows: [],
    artifacts: null,
  };
  let historyEntries = [];
  let transcriptEntries = [];
  let transcriptSessionIds = [];

  const post = (msg) => {
    switch (msg.type) {
      case 'status':
      case 'sessionIndex':
        break;
      case 'history':
        historyEntries = historyEntries.concat(msg.entries);
        break;
      case 'transcriptEntries':
        transcriptEntries = transcriptEntries.concat(msg.entries);
        transcriptSessionIds = transcriptSessionIds.concat(msg.sessionIds);
        break;
      case 'tokens':
        folded.tokenData = folded.tokenData.concat(msg.data);
        break;
      case 'tools':
        folded.toolData = folded.toolData.concat(msg.data);
        break;
      case 'inventories':
        folded.toolInventories = folded.toolInventories.concat(msg.data);
        break;
      case 'timelines':
        folded.timelines = folded.timelines.concat(msg.data);
        break;
      case 'apiErrors':
        folded.apiErrors = folded.apiErrors.concat(msg.data);
        break;
      case 'permissions':
        folded.permissionRows = folded.permissionRows.concat(
          msg.data.flatMap((p) => p.perModeEntries)
        );
        folded.permissionChanges = folded.permissionChanges.concat(
          msg.data.flatMap((p) => p.changes)
        );
        break;
      case 'agentSettings':
        folded.agentSettings = folded.agentSettings.concat(msg.data);
        break;
      case 'attribution':
        folded.attribution = folded.attribution.concat(msg.data);
        break;
      case 'runtime':
        folded.runtimeEvents = folded.runtimeEvents.concat(msg.data);
        break;
      case 'churnGeometry':
        folded.churnGeometry = folded.churnGeometry.concat(msg.data);
        break;
      case 'valueFlow':
        folded.valueFlow = folded.valueFlow.concat(msg.data);
        break;
      case 'memories':
        folded.memories = msg.data;
        break;
      case 'workflows':
        folded.workflows = msg.data;
        break;
      case 'artifacts':
        folded.artifacts = msg.data;
        break;
      default:
        throw new Error(`unhandled upload emit type: ${msg.type}`);
    }
  };

  const summary = await buildUploadDataset(
    [{ blob: new Blob([zipBytes]), name: 'corpus.zip' }],
    post,
    { yielding: false }
  );
  folded.entries = unionEntries(historyEntries, transcriptEntries, transcriptSessionIds);
  return { folded, summary };
}

// ── Normalization: apply the server's DECLARED shaping to the SPA side and ──
// ── strip the server's provenance stamps, then sort both deterministically ──

// Provenance stamps the server adds to every value; always normalized away
// (multi-source addressing has no meaning for a single uploaded bundle).
const PROVENANCE_KEYS = ['sourceId', 'harness'];

function stripKeys(value, keys) {
  const drop = new Set([...PROVENANCE_KEYS, ...keys]);
  return JSON.parse(
    JSON.stringify(value, (key, v) => (drop.has(key) ? undefined : v))
  );
}

function sortRows(rows) {
  return [...rows]
    .map((r) => JSON.stringify(r))
    .sort()
    .map((s) => JSON.parse(s));
}

async function normalizeSides(key, spaRows, serverRows) {
  let spa = spaRows;
  if (key === 'timelines') {
    const { slimSessionTimeline } = await import('../src/lib/parse-timeline.ts');
    spa = spa.map((t) => slimSessionTimeline(t));
  }
  if (key === 'toolData') {
    const { stripToolCommandBodies } = await import('../src/lib/parse-tools.ts');
    spa = spa.map((t) => stripToolCommandBodies(t));
  }
  const fieldDrops = FIELD_NORMALIZE[key] ?? [];
  return {
    spa: sortRows(stripKeys(spa, fieldDrops)),
    server: sortRows(stripKeys(serverRows, fieldDrops)),
  };
}

// ── The gate ──────────────────────────────────────────────────────────────

test('SPA upload parse and server ingest agree over the same ~/.claude tree (#2951)', async () => {
  const corpus = buildSampleCorpus();
  // Exercise the history∪transcript UNION fallback: a session that appears in
  // history.jsonl with NO transcript file. Every sample session has a
  // transcript, so without this the "keep the history entry for a
  // transcript-less session" branch — of both unionEntries (SPA) and the
  // server's `!transcriptSessionIds.has(...)` filter — never fires, and the
  // parity claim over `entries` would silently miss a real divergence there.
  // corpus.historyJsonl feeds BOTH sides (buildServerHome + corpusZipEntries),
  // so appending one line covers both.
  const historyOnly = {
    display: 'A prompt whose session left no transcript on disk.',
    pastedContents: {},
    timestamp: 1_779_000_000_000,
    project: '-home-dev-acme-web',
    sessionId: '20260517-9999-history-only-sample',
  };
  corpus.historyJsonl += JSON.stringify(historyOnly) + '\n';

  const zipBytes = zipSync(corpusZipEntries(corpus), {
    level: 0,
    mtime: new Date('2026-01-01T00:00:00Z'),
  });
  const home = buildServerHome(corpus);
  let dbPath;
  try {
    const server = await runServerPipeline(home);
    dbPath = server.dbPath;
    const { folded, summary } = await runUploadPipeline(zipBytes);
    assert.ok(summary.usableFiles > 0, 'upload pipeline found no usable files');

    // The union fallback is actually exercised: the transcript-less session's
    // history entry survives on BOTH sides (if either dropped it, the entries
    // deep-equal below would fail; this asserts the branch ran at all).
    const historyOnlyId = '20260517-9999-history-only-sample';
    assert.ok(
      folded.entries.some((e) => e.sessionId === historyOnlyId),
      'SPA union dropped the transcript-less history entry — fallback branch not exercised'
    );
    assert.ok(
      (server.dataset.entries ?? []).some((e) => e.sessionId === historyOnlyId),
      'server union dropped the transcript-less history entry — fallback branch not exercised'
    );

    // 1) Full classification: every server dataset key is exactly one of
    //    parity / server-only / fixture-empty. A new assembleDataset() key
    //    fails here until it is consciously classified.
    const serverKeys = Object.keys(server.dataset);
    const classified = new Set([
      ...PARITY_KEYS,
      ...Object.keys(SERVER_ONLY_KEYS),
      ...FIXTURE_EMPTY_KEYS,
    ]);
    const unclassified = serverKeys.filter((k) => !classified.has(k));
    assert.deepEqual(
      unclassified,
      [],
      `assembleDataset() keys not classified in the #2951 parity inventory: ${unclassified.join(', ')} — add each to PARITY_KEYS, SERVER_ONLY_KEYS (with a reason), or FIXTURE_EMPTY_KEYS`
    );
    // Keys spread into the return object only when their opt-in flag or data
    // source exists (the flag-off byte-identical rule): absent here is fine,
    // but when present they are already classified above.
    const CONDITIONAL_KEYS = new Set([
      'gitOutcomes',
      'docIssueSnapshot',
      'localCalibration',
      'recommendations',
      'memories',
    ]);
    const phantom = [...classified].filter(
      (k) => !serverKeys.includes(k) && !CONDITIONAL_KEYS.has(k)
    );
    assert.deepEqual(
      phantom,
      [],
      `classified keys no longer returned by assembleDataset(): ${phantom.join(', ')}`
    );

    // 2) Parity keys: deep-equal after declared shaping + provenance strip.
    for (const key of PARITY_KEYS) {
      const spaRows = folded[key];
      const serverRows = server.dataset[key] ?? [];
      const { spa, server: srv } = await normalizeSides(key, spaRows, serverRows);
      assert.equal(
        spa.length,
        srv.length,
        `${key}: SPA produced ${spa.length} row(s), server ${srv.length}`
      );
      assert.deepEqual(
        spa,
        srv,
        `${key}: SPA and server rows diverge after declared normalization`
      );
    }

    // 3) Fixture-empty keys: both sides yield nothing for this fixture, so a
    //    server-side source of any of these NOT visible to the upload path
    //    would surface here as an asymmetry.
    for (const key of FIXTURE_EMPTY_KEYS) {
      const serverVal = server.dataset[key];
      const emptyServer =
        serverVal == null ||
        (Array.isArray(serverVal) && serverVal.length === 0) ||
        (typeof serverVal === 'object' && Object.keys(serverVal).length === 0);
      assert.ok(
        emptyServer,
        `${key}: expected empty from the transcripts+history fixture, server produced ${JSON.stringify(serverVal)?.slice(0, 200)}`
      );
    }
  } finally {
    rmSync(home, { recursive: true, force: true });
    // Remove the throwaway SQLite db and its node:sqlite -wal/-shm sidecars.
    if (dbPath) {
      for (const suffix of ['', '-wal', '-shm']) {
        rmSync(`${dbPath}${suffix}`, { force: true });
      }
    }
  }
});
